[tool.poetry]
name = "medkit"
version = "0.1.0"
description = "A Python library for a learning health system"
readme = "README.md"
repository = "https://gitlab.inria.fr/heka/medkit/"
documentation = "https://heka.gitlabpages.inria.fr/medkit/"
authors = ["HeKA Research Team"]
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Medical Science Apps."
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0" # Add <4.0 for smart-open
flashtext = "^2.7"
pyaml = "^21.10.1"
requests = "^2.28.1"
smart-open = "^5.2.1"
typing-extensions = "^4.1.1"
Unidecode = "^1.3.4"

torch = {version = "^1.12.0", optional = true}
transformers = {extras = ["sentencepiece"], version = "^4.20.1", optional = true}
sacremoses = {version = "^0.0.53", optional = true}
PyRuSH = {version = "^1.0.3", optional = true}
quickumls = {version = "^1.4.0", optional = true}
packaging = {version = "^21.3", optional = true}
spacy = {version = "^3.4.0", optional = true}

jupyter-book = {version = "^0.13.0", optional = true}
matplotlib = {version = "^3.5.2", optional = true}
# TODO: to be added for supporting `autodoc_typehints_format` when poetry 1.2
# cf.https://github.com/sphinx-doc/sphinx/issues/10241
# cf. https://python-poetry.org/docs/master/managing-dependencies/#dependency-groups
# sphinx = {version = "^4.3.3", optional = true}
sphinxcontrib-mermaid = {version = "^0.7.1", optional = true}
sphinx-toolbox = {version = "^3.1.2", optional = true}


[tool.poetry.dev-dependencies]
black = "^22.6.0"
flake8 = "^4.0.1"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-mock = "^3.8.2"

[tool.poetry.extras]
docs = [
    "jupyter-book",
    "matplotlib",
#    "sphinx",
    "sphinxcontrib-mermaid",
    "sphinx-toolbox",
    "spacy"
]

hf-translator = [
    "sacremoses",  # needed by default model "Helsinki-NLP/opus-mt-fr-en"
    "torch",
    "transformers"
]
optional = [
    "PyRush",
    "packaging",  # needed to check quickumls version
    "quickumls",
    "spacy"
]

# Waiting for --all-extras (https://github.com/python-poetry/poetry/pull/5452)

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
preview = true
extend-exclude = ".env"
