name: medkit-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.7
  - jupyter-book
  - matplotlib
  - sphinxcontrib-mermaid
  - sphinx-toolbox
  - pip
  - pip:
      - spacy
      - -e ..


