name: Prepare Poetry environment
description: Install poetry
author: HeKA research team
inputs:
  home:
    description: POETRY_HOME
    required: false
    default: '/etc/poetry'
runs:
  using: "composite"
  steps:
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | POETRY_HOME=${{ inputs.home }} python3 -
        export PATH=$PATH:$POETRY_HOME/bin
        echo "$PATH" >> $GITHUB_PATH
        poetry --version
        poetry env use python3.7
        poetry env info
      shell: bash
